### ISSUE TITLE
Issue converting to Seurat object 

### ISSUE THREAD

**Issue by mdeea** [limfuxing/ruvIIInb#10] opened 2023-05-09 08:15 UTC
Thanks for this package and the great tutorial.

My current workflow is based around Seurat, so I would like to be able convert to a Seurat object after normalization, however I'm getting an error with the as.Seurat() command
specifically

seurat_ruv3nb <- as.Seurat(sce_ruv3nb, counts = "counts", data ="logPAC")

Error in UseMethod(generic = "as.sparse", object = x) :
no applicable method for 'as.sparse' applied to an object of class "c('DelayedMatrix', 'DelayedArray', 'DelayedUnaryIsoOp', 'DelayedUnaryOp', 'DelayedOp', 'Array', 'RectangularData')"

It seems to be specifically objecting to this sce object, because I can successfully do the conversion if I use one I have created recently myself.

It is possible this is related to upgrade of the Matrix package in Nov 2022. I have had some issues with other packages.

Any help appreciated.

**Comment by limfuxing** [comment] 2023-05-10 06:44
Could it because the 'logPAC' slot is in DelayedArray format? Could you try converting the slot to matrix first using 

assays(sce,withDimnames=FALSE )$tmp <- as.matrix(assays(sce)$logPAC)
then
seurat_ruv3nb <- as.Seurat(sce_ruv3nb, counts = "counts", data ="tmp")

**Comment by CathyXD** [comment] 2023-05-24 02:59
Hi, team 
 I also encounter some issues when transferring the sce to seurat. The error shows 
> seurat_ruv3nb <- as.Seurat(sce_ruv3out2, counts = "counts", data ="logPAC")
Error: No data in provided assay - counts
> sce_ruv3out2@assays
An object of class "SimpleAssays"
Slot "data":
List of length 4
names(4): counts logcounts pearson logPAC

counts(sce_ruv3out2)
Error in value[[3L]](cond) : 
  'assay(<SingleCellExperiment>, i="character", ...)' invalid subscript 'i'
file '/tmp/RtmpbXUmcD/HDF5Array_dump/auto00004.h5' does not exist

 I wondering how to call out the corresponding matrix then.

**Comment by limfuxing** [comment] 2023-05-24 08:57
This error sometimes happened because the assays data in the SCE object has been stored in DelayedArray format. We have now decided to realize the assays data as sparseMatrix object. Please install the latest version (v 0.7.8.8) from GitHub and rerun makeSCE followed by Seurat conversion. Let me know if you still encounter issues.

**Comment by mdeea** [comment] 2023-05-25 04:43
> Could it because the 'logPAC' slot is in DelayedArray format? Could you try converting the slot to matrix first using
> 
> assays(sce,withDimnames=FALSE )$tmp <- as.matrix(assays(sce)$logPAC) then seurat_ruv3nb <- as.Seurat(sce_ruv3nb, counts = "counts", data ="tmp")

Thanks! that was the issue.
with the additional aid of this thread
https://github.com/satijalab/seurat/issues/3133
I was able to sort it out. But will also try the new version.

**Comment by CathyXD** [comment] 2023-05-25 05:03
Yes, the new version work well with Seurat now! 
Thank you :) 

> This error sometimes happened because the assays data in the SCE object has been stored in DelayedArray format. We have now decided to realize the assays data as sparseMatrix object. Please install the latest version (v 0.7.8.8) from GitHub and rerun makeSCE followed by Seurat conversion. Let me know if you still encounter issues.

**Comment by limfuxing** [comment] 2023-05-26 04:09
I'm glad the issue is resolved @CathyXD  @mdeea. I am closing this now.

**Closed** 2023-05-26 04:10 UTC
